### ISSUE TITLE
EGE 20.0a 开发记录

### ISSUE THREAD

**Issue by chirsz-ever** [wysaid/xege#11]
- [x] #9 
- [x] #10 
- [x] 使 `ege::getimage` 支持从资源文件中加载 `png` 图片
- [x] 自动初始化，使 `ege::newimage` 可在 `initgraph` 之前进行

**Comment by wysaid** [comment]
- [ ] 文本框支持数字输入,  解决萌新经常问到的获取一个数字的问题。

**Comment by chirsz-ever** [comment]
- [ ] 实现 `getGraphicsVer`

**Comment by GWMforget1997** [comment]
- [ ] putpixels和putpixels_f像素颜色赋值方式修正，由BGR改为RGB

- [ ] sys_edit类中的visable函数名修正为visible

- [ ] setlinewidth()仅仅是设置一下线宽参数，实际需要在setcolor调用后生效，修正为立即生效

- [ ] 文字输出时，使用默认样式，空格会占用非常小的宽度，需要手动添加文字大小设置才能调整至一个字符大小，建议默认设置，以保证对齐

- [ ] ege_setalpha, PIMAGE参数为NULL时，程序会崩溃退出

- [ ] setlinestyle()，当线宽大于1时，线型失效

**Comment by GWMforget1997** [comment]
键码key_code_e中的小键盘的符号键缺少定义, 虚拟键码中为0x6A-0x6F

**Comment by GWMforget1997** [comment]
- [ ] 键码key_code_e中的小键盘的符号键缺少定义, 虚拟键码中为0x6A-0x6F

**Comment by GWMforget1997** [comment]
- [ ] 添加移动窗口

**Comment by GWMforget1997** [comment]
- [ ] clearviewport清除视口区域是直接用bar糊上去的，这样颜色实际是填充颜色，建议修正为用背景颜色填充。

**Comment by GWMforget1997** [comment]
- [ ] EGE中的getch()只能用于EGE的窗口，对于控制台无法阻塞，由于conio.h的包含问题，建议内部增加控制台的getch_console()函数

**Comment by TheBadZhang** [comment]
建议 **puimage** 整合一下 **putimage_withalpha**

**Comment by GWMforget1997** [comment]
- [ ] setcolor中进行了过多操作，且函数本身并没有其它作用，建议先使用getcolor()进行颜色对比，如果不同再进行颜色设置操作。

**Comment by GWMforget1997** [comment]
- [ ] 增加HDC getHdc(PIMAGE  pimg = NULL)函数，用于获取图像或窗口帧缓存的HDC

**Comment by wysaid** [comment]
- [ ] 解决 newimage 在  initgraph 之前会崩溃的问题, 可能的解决办法:
    - newimage调用时判断一下initgraph有没有调用, 如果没有, 自动创建一个隐藏窗口
- [ ] 在解决 newimage 崩溃的问题基础上, 开放 ``class Image`` 支持 cpp 的方式使用 ege

**Comment by royqh1979** [comment]
> * [x]  增加HDC getHdc(PIMAGE  pimg = NULL)函数，用于获取图像或窗口帧缓存的HDC

请问这个的用处是啥？我看现在EGECOLOR里面缺省把颜色的alpha通道都设成了255。而gdi操作在alpha通道不是0的时候无法正常工作，有HDC也没啥用啊？

**Comment by TheBadZhang** [comment]
> > * [x]   增加HDC getHdc(PIMAGE  pimg = NULL)函数，用于获取图像或窗口帧缓存的HDC
> 
> 请问这个的用处是啥？我看现在EGECOLOR里面缺省把颜色的alpha通道都设成了255。而gdi操作在alpha通道不是0的时候无法正常工作，有HDC也没啥用啊？

请问你愿意提交一下用你的代码创建一个 issue，然后指出问题么？感谢

**Comment by royqh1979** [comment]
抱歉，测试了一下BitBlt和PlgBlt都没问题

贱人张 <notifications@github.com> 于2020年10月8日周四 上午11:43写道：
