### ISSUE TITLE
关于字符串编码

### ISSUE THREAD

**Issue by chirsz-ever** [wysaid/xege#123]
目前的实现：相关 API 有接受 `LPSTR` 和 `LPWSTR`，也就是 `char*` 和 `wchar_t*` 的两套重载，`char*` 接受 ANSI 编码，`wchar_t` 接受 UTF-16 编码，直接对应相关 Win32 API。

目前的需求：支持使用 UTF-8 （特别是 clang）。

计划：参考 [DxLib](https://dxlib.xsrv.jp/)，添加 `setencode` API 或者 `INIT_UTF8` 初始化参数来控制应当接受的字符串编码，默认行为仍使用 ANSI 编码。

源代码希望完全使用 UTF-8，但需要考虑是否添加 BOM，以及在各编译器下测试。

**Comment by wysaid** [comment]
不带BOM 的才是科学的做法， 但是vs似乎不识别不带BOM的， 会不会导致别人打开乱码？
当然， 直接合我觉得也OK。   正常开发者应该有能力解决这个问题。
