### ISSUE TITLE
允许初始化时隐藏窗口

### ISSUE THREAD

**Issue by chirsz-ever** [wysaid/xege#124]
可以添加一个 `INIT_HIDEWINDOW` 初始化参数，在调用 `initgraph` 时隐藏窗口，调整窗口位置，和初始化窗口内容后再显示窗口。

**Comment by wysaid** [comment]
可以是可以， 这个解决的问题是防止用户在 initgraph 之前 newimage吧， 但也解决不了用户写全局变量直接 = newimage...
要能直接给 Image 这个类添加一个延迟初始化的实现， 才可能比较好解决这个问题

**Comment by yixy-only** [comment]
#138
