### ISSUE TITLE
建议添加ege的代码规范、请求规范、文档规范

### ISSUE THREAD

**Issue by c-cpp-a** [wysaid/xege#134]
现状：
1. ege库新老代码风格不太一致，容易让尝试理解代码者感到困惑，不十分容易修改和发现问题；
2. 贡献者的码风没有约束，造成割裂感；
3. 有的函数并不在声明时附带功能注释，用户只能翻看相关文档，离线用户的使用体验打折扣；
4. 没有整套的issues规范，降低沟通效率；
5. 文档没有专人撰写，更新较慢，教程较为跳跃。

因此，我提议ege增加一整套完整的相关规范，增加效率，降低修改难度。

**Comment by c-cpp-a** [comment]
除此之外，我发现还有一些函数从功能注释来看是执行了完全相同的功能，应该还是新老API的差异？

**Comment by wysaid** [comment]
嗯， 很久没改了， 但ege是比较开放的， 欢迎楼主来提交你的改动， 你可以邀请几位维护的人一起来review看看
