### ISSUE TITLE
对PIMAGE对象执行resize方法时出现预期外行为

### ISSUE THREAD

**Issue by chirsz-ever** [wysaid/xege#2]
如果执行resize时width=0，那么接下来的行为是预期外的。
我的编译平台是VS2015 x86，EGE版本是19.01
复现代码：
```cpp
#include <ege.h>
using namespace std;
using namespace ege;

int main() {

	initgraph(640, 480);
	setbkcolor(WHITE);

	PIMAGE tmp = newimage();
	setbkcolor(BLUE, tmp);
	
	resize(tmp, 40, 40);
	putimage(270, 190, tmp);

	resize(tmp, 20, 20);
	putimage(350, 190, tmp);

	resize(tmp, 20, 40);
	putimage(270, 250, tmp);

	resize(tmp, 40, 40);
	putimage(350, 250, tmp);
	
	getch();

	ege::delimage(tmp);
	return 0;
}
```
效果：
![qq 20190202152245](https://user-images.githubusercontent.com/31474766/52161350-d5adda00-26fe-11e9-8ab3-21115a898320.png)
如果把第三次putimage中width改为0：
```cpp
#include <ege.h>
using namespace std;
using namespace ege;

int main() {

	initgraph(640, 480);
	setbkcolor(WHITE);

	PIMAGE tmp = newimage();
	setbkcolor(BLUE, tmp);
	
	resize(tmp, 40, 40);
	putimage(270, 190, tmp);

	resize(tmp, 20, 20);
	putimage(350, 190, tmp);

	resize(tmp, 0, 40);
	putimage(270, 250, tmp);

	resize(tmp, 40, 40);
	putimage(350, 250, tmp);
	
	getch();

	ege::delimage(tmp);
	return 0;
}
```
![qq 20190202152805](https://user-images.githubusercontent.com/31474766/52161407-83b98400-26ff-11e9-899c-d2147442741d.png)
可见第四次putimage出现异常。
经检查，把height设为0并不会出现异常。

**Comment by chirsz-ever** [comment]
fixed by #28

**Comment by FrankHB** [comment]
没有挂掉的 0 在 GDI 的意义上仍然是无意义的，只是因为 DIB header 要求的值不直接是图像的高度，多出来特殊处理才导致不同。

根本上 `resize` 输入非正数就是错的，需要检查输入合法性。

Suggest reopen.

**Comment by wysaid** [comment]
> 没有挂掉的 0 在 GDI 的意义上仍然是无意义的，只是因为 DIB header 要求的值不直接是图像的高度，多出来特殊处理才导致不同。
> 
> 根本上 `resize` 输入非正数就是错的，需要检查输入合法性。
> 
> Suggest reopen.

确实无意义...   要咋改呢,  报个错？

**Comment by FrankHB** [comment]
@wysaid 可以报错，不过这个就涉及到其它地方怎么报错的问题。

或者直接 narrowed contract ，加断言。
