### ISSUE TITLE
Please add compile option for demo project

### ISSUE THREAD

**Issue by ChivenZhang** [wysaid/xege#245]
I integrated the repository to my visual studio project, and it occured lots of executable program in list which made it hard to choose. So I think it would be better to control whether to compile demos. That's all, thanks.

![image](https://github.com/user-attachments/assets/ba521569-f74e-467d-b5bf-cb95eb20e1c1)

![image](https://github.com/user-attachments/assets/67a3fd8f-62d4-4149-84d6-eaec7cc178e2)

**Comment by yixy-only** [comment]
@ChivenZhang  Thanks for your suggestion. Do you have any good solution for this?

**Comment by ChivenZhang** [comment]
> @ChivenZhang Thanks for your suggestion. Do you have any good solution for this?

https://github.com/protocolbuffers/protobuf/blob/main/CMakeLists.txt#L28
This is google's protobuf project. It may be provide a good idea to handle the problem.

**Comment by yixy-only** [comment]
> > @ChivenZhang Thanks for your suggestion. Do you have any good solution for this?
> 
> https://github.com/protocolbuffers/protobuf/blob/main/CMakeLists.txt#L28 This is google's protobuf project. It may be provide a good idea to handle the problem.

@ChivenZhang  OK, thank you for your help. I will reply to you after the processing is completed.

**Comment by yixy-only** [comment]
@ChivenZhang Now that I have updated the commit #247 , you can see if the issue is solved. You may need to delete the CMake configuration cache and the "./build" folder.

**Comment by ChivenZhang** [comment]
It works. Thanks.
