### ISSUE TITLE
关于windows下编译无法关闭cmd的问题

### ISSUE THREAD

**Issue by dai-da-da** [wysaid/xege#249]
当我使用devcpp编译，编译出来的 exe 程序无法隐藏cmd窗口，我查看了关于此库的各种办法都无法实现。

**Comment by yixy-only** [comment]
> 当我使用devcpp编译，编译出来的 exe 程序无法隐藏cmd窗口，我查看了关于此库的各种办法都无法实现。

@dai-da-da  这是 GCC 编译器相关的设置，需要在编译参数里加上 -mwindows。如果建的是项目的话，可以在项目属性将项目类型改为 **Win32 图形界面(GUI)程序**，这样就会自动加上这个参数。

**Comment by yixy-only** [comment]
![image](https://github.com/user-attachments/assets/e1c6e9f4-c2b8-46a3-a9bc-f1b118f63246)
