### ISSUE TITLE
inputbox_getline窗口发黑

### ISSUE THREAD

**Issue by SadLava** [wysaid/xege#44]
代码如下：
```cpp
#include "ege.h"
#include <wchar.h>

using namespace ege;
using namespace std;

int main() {
	initgraph(640, 640, 0);
	wchar_t text[1024];
	setcolor(GREEN);
	inputbox_getline(L"测试", L"测试", text, 1024);
	xyprintf(0, 0, text);
	getch();
	return 0;
}
```
运行截图：
![QQ截图20200905180256](https://user-images.githubusercontent.com/47706037/92302864-53ecf500-efa2-11ea-8c06-d2c32ac02f3c.png)
使用的是**官网版本**，编译环境vs2019 x64（疑似官网版本标题字符串存在问题）

**Comment by wysaid** [comment]
修好了要更新个版本么, 20.09 ?

**Comment by SadLava** [comment]
（我觉得这个问题确实大到需要紧急更新了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wang&amp;nbsp;Yang"<notifications@github.com&gt;; 
发送时间: 2020年9月11日(星期五) 下午4:03
收件人: "wysaid/xege";
抄送: "Author";
主题: Re: [wysaid/xege] inputbox_getline窗口发黑 (#44)





 
修好了要更新个版本么, 20.09 ?
 
&mdash;

**Comment by wysaid** [comment]
所以 @chirsz-ever 来一个 ``20.09`` ?

**Comment by chirsz-ever** [comment]
我觉得维持版本名不变，改 20.08-rc1 吧。
当初发测试版时没多少人用，现在正式发版了才找出 BUG……

**Comment by royqh1979** [comment]
inputbox是不是直接用windows自己的对话框来实现更好点？Borland C的时候这么干是没办法，现在其实没必要自己在窗口中画了呀。
