### ISSUE TITLE
MinGW 配置ege执行程序失败 

### ISSUE THREAD

**Issue by Snail1998** [wysaid/xege#8]
**MinGW 安装如下**
![图片](https://user-images.githubusercontent.com/38743246/72679176-b5318800-3ae7-11ea-87e5-488d5038d670.png)

当我配置时选择ege 19.01 中mingw64的libgraphics64.a时，执行下述程序会报错
![图片](https://user-images.githubusercontent.com/38743246/72679252-6d5f3080-3ae8-11ea-8cc1-d31512cfcade.png)
![图片](https://user-images.githubusercontent.com/38743246/72679269-98498480-3ae8-11ea-8314-585291045b2b.png)

当我选择ege 13.04中mingw4.7.2的libgraphics.a时，执行同样的程序不会报错但仅弹出如下图所示窗口，未显示代码中的圆并直接退出了。
![图片](https://user-images.githubusercontent.com/38743246/72679487-9254a300-3aea-11ea-9b5f-b1145a4c3cc5.png)

试了很多办法都不行，求助！

**Comment by wysaid** [comment]
官网有[配置教程](https://xege.org/beginner-lesson-1.html)的

**Comment by Snail1998** [comment]
谢谢您的回复！

我是按照官网的配置教程下载了ege 19.01包，解压缩后将include/和lib/路径下的文件添加到MinGW对应的路径下，配置完成后情况如上述所示，尝试选择不同版本的libgraphics.a一个会报错，另一个会弹出窗口但不会显示内容。

另外我使用的编辑器是VS Code，这个会有影响吗？

**Comment by chirsz-ever** [comment]
你下的是 32 位版本的 mingw 吧，要用 32 位版本的 EGE 库 ，`libgraphics.a`。
另外，个人推荐使用 [TDM-GCC](https://jmeubank.github.io/tdm-gcc/)

**Comment by Snail1998** [comment]
> 
> 
> 你下的是 32 位版本的 mingw 吧，要用 32 位版本的 EGE 库 ，`libgraphics.a`。
> 另外，个人推荐使用 [TDM-GCC](https://jmeubank.github.io/tdm-gcc/)

谢谢您的回复，抱歉前段时间一直没来得及试！

我试了32位版本的ege库也不行，怀疑是我的mingw没有装完整，于是我按照您的建议安装了TDM-GCC，配置之后可以正常使用了，非常感谢！
