### ISSUE TITLE
cmake

### ISSUE THREAD

**Issue by HUGHNew** [wysaid/xege#94]

**Comment by HUGHNew** [comment]
```cmake
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_C_COMPILER:

    cl

  is not a full path and was not found in the PATH.
```

此外 cmakelists.txt 没有 `project`  和 `cmake_minimum_required`

**Comment by chirsz-ever** [comment]
是按照 [BUILD.md](https://github.com/wysaid/xege/blob/master/BUILD.md) 编译的吗？

我猜你是在 `src` 目录下执行的 `cmake`，但本项目的 `CMakeLists.txt` 直接放在项目根目录下，应直接对项目根目录运行 `cmake`。

如果以上没有解决你的问题，请提供更详细的消息，阐明具体使用的命令和执行命令的当前目录。

**Comment by HUGHNew** [comment]
## Step one

下载Release源码包20.08 解压到一个目录的`third/ege`下

## Step two

执行指令

```powershell
cd third/ege
mkdir build
cd build
cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
```

执行完上一条指令后 主要是以下的报错信息

```text
  Cannot specify sources for target "xege" which is not built by this
  project.


CMake Error at CMakeLists.txt:23 (target_compile_definitions):
  Cannot specify compile definitions for target "xege" which is not built by
  this project.


CMake Error at CMakeLists.txt:49 (target_link_libraries):
  Cannot specify link libraries for target "xege" which is not built by this
  project.
```

然后自己手动添加过 `project(ege)` 和 `cmake_minimum_required(VERSION 2.8)` 到 CMakelists.txt (**third/ege**下那个 即根目录下) 报错的问题是 project 没有构建之类的错

**Comment by chirsz-ever** [comment]
这里的第 23 行应该是 `src/CMakeLists.txt` 里的第 23 行，这还是直接在 `src` 里构建。

你是在哪里下载代码的？如果你是在 [Release 页面](https://github.com/wysaid/xege/releases) 下载的代码压缩包，应该是包含整个项目的。

**Comment by HUGHNew** [comment]
懂了 是我复制的时候只复制了src 当时看了看其他几个文件 没太注意到根目录还有个cmakelists
现在没问题了
